#!/usr/bin/env python3

# Copyright (c) 2017-2018 Samuel Thibault <samuel.thibault@ens-lyon.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY Samuel Thibault ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

import sys
import pygame
import argparse
import logging
import socket
import select
import threading
import os
import crypt

is_server = False

map = [ [ ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' ],
        [ ' ', 'X', 'X', 'X', 'X', 'X', 'X', ' ', 'X', ' ' ],
        [ ' ', 'X', ' ', ' ', ' ', 'S', ' ', ' ', 'X', ' ' ],
        [ ' ', 'X', ' ', 'X', ' ', 'X', 'X', ' ', 'X', '2' ],
        [ '1', 'X', ' ', 'X', 'A', 'X', 'X', ' ', 'X', ' ' ],
        [ ' ', 'X', ' ', 'X', ' ', ' ', ' ', ' ', 'X', ' ' ],
        [ ' ', 'X', ' ', 'X', 'X', 'X', 'X', 'X', 'X', ' ' ],
        [ ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' ] ]

width = len(map[0])
height = len(map)

# This is the sprites size
unit = 64
grass = (0x00, 0x90, 0x00)

u_attr = []
# user0 is current one
u_attr.append({
    'key': '',
    'move': ''
})


# Parse arguments
def parse_args():
    parser = argparse.ArgumentParser(description="A little game about adam and Eve")
    parser.add_argument('-s','--server',
            help="Connect to server",
            dest='server')

    parser.add_argument('-p', '--port',
            type=int,
            help='Port of the server. If not specified, `7777` is used')

    parser.add_argument('-d','--debug',
            help="Priont output messages",
            action='store_true',
            dest='debug')

    return parser.parse_args()


args = parse_args()

# Initialize socket
so = socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
so_list = []
port = 7777

if args.port:
    port = args.port
if args.server:
    opponent_so = socket.create_connection((args.server, port))
else:
    is_server = True
    so.bind(('', port))
    so.listen(1)

# Waiting for opponent to connect if this is the server. Bypass if not
if is_server:
    print('Waiting for opponent to connect...')
    opponent_so, opponent_addr = so.accept()

# Creating u_attr for opponent
u_attr.append({'ready': False,
               'hashed_move': '',
               'key': '',
               'move': ''
               })

# Pygame initialization
pygame.init()
screen = pygame.display.set_mode( (unit * width, unit * height) )
alpha = 128

# Load resources
woman = pygame.image.load("image/woman.png")
woman_ghost = woman.copy()
woman_ghost.fill((255, 255, 255, alpha), None, pygame.BLEND_RGBA_MULT)
woman_coords = [ 0, 0 ]
man = pygame.image.load("image/man.png")
man_ghost = man.copy()
man_ghost.fill((255, 255, 255, alpha), None, pygame.BLEND_RGBA_MULT)
man_coords = [ 0, 0 ]

snake = pygame.image.load("image/snake.png")
snake_ghost = snake.copy()
snake_ghost.fill((255, 255, 255, alpha), None, pygame.BLEND_RGBA_MULT)
snake_coords = [ 0, 0 ]

stone = pygame.image.load("image/stone.png")
stone_coords = [ 0, 0 ]

apple = pygame.image.load("image/apple.png")
apple_coords = [ 0, 0 ]

woman_move = [ 0, 0 ]
man_move = [ 0, 0 ]
snake_move = [ 0, 0 ]

# Initialize positions
def init():
    def find(coords, c):
        for y in range(len(map)):
            for x in range(len(map[y])):
                if map[y][x] == c:
                    coords[0] = x
                    coords[1] = y
                    return
        raise Exception('oops')

    find(woman_coords, '1')
    find(man_coords, '2')
    find(snake_coords, 'S')
    find(apple_coords, 'A')


# Listening thread function
def socket_thread():
    # Process command receive
    def process_command(msg, attr):
        import re
        command, args = re.search(r"^/([\S]*)[\s](.*)", msg).group(1, 2)
        if command == "move":
            logging.debug("Move command receive hashed move : %s" % (args))
            if not attr['hashed_move']:
                attr['hashed_move'] = args
            else:
                logging.debug("move already set for this player")
        elif command == "key":
            logging.debug("Key verification message receive")

    global woman_move
    global man_move
    global snake_move
    print(so_list)
    while True:
        rea, wri, exc = select.select(so_list, [], [])
        for item in rea:
            message = item.recv(1024)
            logging.info('opponent message recieved %s' % (message))
            if message == b'':
                so_list.remove(item)
            else:
                process_command(message.decode('utf-8'), u_attr[1])


# Launching the listening thread
so_list.append(opponent_so)
threading.Thread(None, socket_thread).start()


init()

log_f = '%(levelname)s:%(message)s'

if not args.debug:
    logging.basicConfig(format=log_f, level=logging.ERROR)
else:
    logging.basicConfig(format=log_f, level=logging.DEBUG)
    logging.debug("Debug mode activated")

while True:
    e = pygame.event.wait()

    # Check for exit
    if e.type == pygame.QUIT:
        sys.exit()
    if u_attr[0]['key'] == "":
       u_attr[0]['key'] = "%02x" % ord(os.urandom(1))

    elif e.type == pygame.KEYDOWN:
        if is_server:
            # Check for woman movements
            if woman_move == [ 0, 0 ]:
                if e.key == pygame.K_UP:
                    woman_move = [ 0, -1 ]
                    u_attr[0]['move'] = "UP"
                    pass
                elif e.key == pygame.K_DOWN:
                    woman_move = [ 0, 1 ]
                    u_attr[0]['move'] = "DOWN"
                    pass
                elif e.key == pygame.K_LEFT:
                    woman_move = [ -1, 0 ]
                    u_attr[0]['move'] = "LEFT"
                    pass
                elif e.key == pygame.K_RIGHT:
                    woman_move = [ 1, 0 ]
                    u_attr[0]['move'] = "RIGHT"
                    pass

        else:
            # Check for man movements
            if man_move == [ 0, 0 ]:

                if e.key == pygame.K_UP:
                    man_move = [ 0, -1 ]
                    u_attr[0]['move'] = "UP"
                    pass
                elif e.key == pygame.K_DOWN:
                    man_move = [ 0, 1 ]
                    u_attr[0]['move'] = "DOWN"
                    pass
                elif e.key == pygame.K_LEFT:
                    man_move = [ -1, 0 ]
                    u_attr[0]['move'] =  "LEFT"
                    pass
                elif e.key == pygame.K_RIGHT:
                    man_move = [ 1, 0 ]
                    u_attr[0]['move'] = "RIGHT"
                    pass

        e_move = crypt.crypt(u_attr[0]['move'],u_attr[0]['key'])
        message = "/move " + e_move
        opponent_so.send(message.encode('utf-8'))

    #else:
    #    print(e)


    def move(coords, move):
        return [ coords[0] + move[0], coords[1] + move[1] ]

    # Compute moves
    woman_newcoords = move(woman_coords, woman_move)
    man_newcoords = move(man_coords, man_move)
    snake_newcoords = move(snake_coords, snake_move)

    # But bound to window
    def bound(newcoords, coords, move):
        if newcoords[0] < 0 or newcoords[0] >= width or newcoords[1] < 0 or newcoords[1] >= height:
            # out of bounds
            newcoords[0] = coords[0]
            newcoords[1] = coords[1]
            move[0] = 0
            move[1] = 0

    bound(woman_newcoords, woman_coords, woman_move)
    bound(man_newcoords, man_coords, man_move)
    bound(snake_newcoords, snake_coords, snake_move)

    def collide(newcoords, coords, move):
        if map[newcoords[1]][newcoords[0]] == 'X':
            # Stone
            newcoords[0] = coords[0]
            newcoords[1] = coords[1]
            move[0] = 0
            move[1] = 0

    # Prevent collisions with stones
    collide(woman_newcoords, woman_coords, woman_move)
    collide(man_newcoords, man_coords, man_move)

    # Prevent collisions between players
    if woman_newcoords == man_newcoords:
        woman_newcoords = woman_coords
        woman_move = [ 0, 0 ]
        man_newcoords = man_coords
        man_move = [ 0, 0 ]

    # Make everybody move when everybody chose her/his direction
    if woman_move != [ 0, 0 ] and man_move != [ 0, 0 ]:
        woman_coords = woman_newcoords
        man_coords = man_newcoords
        snake_coords = snake_newcoords
        woman_move = [ 0, 0 ]
        man_move = [ 0, 0 ]

    #logging.debug("woman at %u,%u to %u,%u" % (woman_coords[0], woman_coords[1], woman_newcoords[0], woman_newcoords[1]))
    #logging.debug("man at %u,%u to %u,%u" % (man_coords[0], man_coords[1], man_newcoords[0], man_newcoords[1]))
    #logging.debug("snake at %u,%u to %u,%u" % (snake_coords[0], snake_coords[1], snake_newcoords[0], snake_newcoords[1]))

    # Display everything
    screen.fill(grass)

    def blit(item, coords):
        screen.blit(item, (unit * coords[0], unit * coords[1]))

    # Display stones
    for y in range(len(map)):
        for x in range(len(map[y])):
            if map[y][x] == 'X':
                blit(stone, (x, y))

    # Display moving items
    blit(apple, apple_coords)

    blit(woman_ghost, woman_newcoords)
    blit(woman, woman_coords)
    blit(man_ghost, man_newcoords)
    blit(man, man_coords)

    blit(snake_ghost, snake_newcoords)
    blit(snake, snake_coords)

    # Show new state
    pygame.display.flip()

    if woman_coords == apple_coords:
        print("woman won!\n")
        sys.exit()
    elif man_coords == apple_coords:
        print("man won!\n")
        sys.exit()

    if woman_coords == snake_coords:
        print("woman lost!\n")
        sys.exit()
    elif man_coords == snake_coords:
        print("man lost!\n")
        sys.exit()
